/**
 * tRPC Router for New Features - Humanized & Wave-Model Ready
 * تم التحديث لإصلاح أخطاء التعريفات (answer) وتوافق استدعاء LLM
 */

import { router, publicProcedure } from '../_core/trpc';
import { z } from 'zod';
import {
  createQuantumEvent,
  calculateAggregatedMetrics,
} from '../utils/eventVectorModel';
import {
  generateEmotionalWeatherReport,
} from '../utils/dailyEmotionalWeather';
import { smartInvokeLLM } from '../engines/smartLLM';

/**
 * Modernized Sample Data using Quantum Wave Structure
 */
const SAMPLE_DATA = [
  {
    topic: 'economy' as const,
    region: 'mena' as const,
    intensity: 0.8,
    polarity: -0.5,
    summary: 'Economic volatility detected in North Africa region.',
    emotions: {
      fear: { amplitude: 0.7, phase: 1.2, superposition: { stable: 0.3, volatile: 0.7 } },
      hope: { amplitude: 0.3, phase: 0.5, superposition: { stable: 0.5, volatile: 0.5 } }
    }
  },
  {
    topic: 'technology' as const,
    region: 'global' as const,
    intensity: 0.9,
    polarity: 0.8,
    summary: 'Breakthroughs in sustainable energy storage systems.',
    emotions: {
      joy: { amplitude: 0.8, phase: 0.2, superposition: { stable: 0.9, volatile: 0.1 } },
      curiosity: { amplitude: 0.9, phase: 0.8, superposition: { stable: 0.7, volatile: 0.3 } }
    }
  }
];

function getSampleVectors() {
  return SAMPLE_DATA.map(data => createQuantumEvent(data));
}

export const newFeaturesRouter = router({
  /**
   * Procedure 1: Emotional Weather
   * Returns Humanized Narrative generated by AI
   */
  getDailyWeather: publicProcedure
    .input(z.object({
      region: z.enum(['global', 'europe', 'mena', 'asia', 'americas', 'africa', 'oceania']).optional(),
    }).optional())
    .query(async ({ input }) => {
      const vectors = getSampleVectors();
      const filtered = input?.region
        ? vectors.filter(ev => ev.region === input.region || ev.region === 'global')
        : vectors;

      const report = await generateEmotionalWeatherReport(filtered);

      return {
        success: true,
        data: report,
      };
    }),

  /**
   * Procedure 2: Universal Q&A
   * Fix: Defined 'answer' and updated smartInvokeLLM params
   */
  answerQuestion: publicProcedure
    .input(z.object({
      question: z.string(),
    }))
    .query(async ({ input }) => {
      const metrics = calculateAggregatedMetrics(getSampleVectors());

      const promptText = `
        As AmalSense, answer this specific question: "${input.question}"
        Current System State: GMI=${metrics.gmi}, CFI=${metrics.cfi}, HRI=${metrics.hri}.
        Context: Be direct, sophisticated, and insightful in English. No points.
      `;

      // تحديث الاستدعاء ليطابق InvokeParams المتوقع (استخدام messages)
      const result = await smartInvokeLLM({
        messages: [{ role: 'user', content: promptText }]
      });

      // استخراج النص من النتيجة بشكل آمن
      const answer = typeof result === 'string'
        ? result
        : (result as any)?.text || "I am currently re-calibrating the consciousness field to provide a precise answer.";

      return {
        success: true,
        answer: answer,
      };
    }),

  /**
   * Procedure 3: Aggregated Metrics
   */
  getAggregatedMetrics: publicProcedure
    .input(z.object({
      region: z.enum(['global', 'europe', 'mena', 'asia', 'americas', 'africa', 'oceania']).optional(),
    }).optional())
    .query(({ input }) => {
      const vectors = getSampleVectors();
      const filtered = input?.region
        ? vectors.filter(ev => ev.region === input.region || ev.region === 'global')
        : vectors;

      return {
        success: true,
        data: calculateAggregatedMetrics(filtered),
      };
    }),
});

export type NewFeaturesRouter = typeof newFeaturesRouter;