/**
 * Sample Historical Events Data
 * 
 * 50+ historical events for Libya and MENA region
 * Includes emotional and economic indicators
 */

export interface HistoricalEventData {
  eventName: string;
  eventDescription: string;
  eventCategory: 'political' | 'economic' | 'social' | 'environmental' | 'technological' | 'health' | 'conflict' | 'cultural' | 'other';
  eventDate: string; // ISO date
  country: string;
  estimatedGMI: number;
  estimatedCFI: number;
  estimatedHRI: number;
  emotionalVector: Record<string, number>;
  gdpImpact: number;
  shortTermOutcome: string;
  mediumTermOutcome: string;
  longTermOutcome: string;
  sources: string[];
}

export const historicalEventsData: HistoricalEventData[] = [
  // Libya Political Events
  {
    eventName: 'Libyan Civil War Begins',
    eventDescription: 'Armed conflict erupts between government forces and various militias',
    eventCategory: 'conflict',
    eventDate: '2014-05-16',
    country: 'Libya',
    estimatedGMI: 25,
    estimatedCFI: 85,
    estimatedHRI: 20,
    emotionalVector: { joy: 5, fear: 85, anger: 75, sadness: 60, hope: 15, curiosity: 40 },
    gdpImpact: -15,
    shortTermOutcome: 'Displacement of civilians, economic collapse',
    mediumTermOutcome: 'International intervention discussions, humanitarian crisis',
    longTermOutcome: 'Prolonged conflict, state fragmentation',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Gaddafi Regime Falls',
    eventDescription: 'Muammar Gaddafi\'s government is overthrown after 42 years',
    eventCategory: 'political',
    eventDate: '2011-08-23',
    country: 'Libya',
    estimatedGMI: 55,
    estimatedCFI: 65,
    estimatedHRI: 70,
    emotionalVector: { joy: 60, fear: 50, anger: 40, sadness: 30, hope: 75, curiosity: 65 },
    gdpImpact: -8,
    shortTermOutcome: 'Transitional government formed, initial optimism',
    mediumTermOutcome: 'Constitutional drafting, security challenges emerge',
    longTermOutcome: 'Political instability, militia proliferation',
    sources: ['Reuters', 'AP News', 'BBC'],
  },
  {
    eventName: 'Benghazi Attack',
    eventDescription: 'U.S. diplomatic compound attacked in Benghazi',
    eventCategory: 'conflict',
    eventDate: '2012-09-11',
    country: 'Libya',
    estimatedGMI: 30,
    estimatedCFI: 80,
    estimatedHRI: 25,
    emotionalVector: { joy: 10, fear: 80, anger: 70, sadness: 75, hope: 20, curiosity: 50 },
    gdpImpact: -5,
    shortTermOutcome: 'International attention, security concerns',
    mediumTermOutcome: 'Increased foreign military presence',
    longTermOutcome: 'Continued instability, militia strengthening',
    sources: ['Reuters', 'CNN', 'BBC'],
  },
  {
    eventName: 'National Dialogue Begins',
    eventDescription: 'UN-sponsored dialogue between Libyan political factions',
    eventCategory: 'political',
    eventDate: '2014-09-01',
    country: 'Libya',
    estimatedGMI: 45,
    estimatedCFI: 70,
    estimatedHRI: 55,
    emotionalVector: { joy: 35, fear: 65, anger: 45, sadness: 40, hope: 60, curiosity: 70 },
    gdpImpact: -2,
    shortTermOutcome: 'Negotiations begin, some optimism',
    mediumTermOutcome: 'Slow progress, disagreements persist',
    longTermOutcome: 'Partial agreements, continued divisions',
    sources: ['UN News', 'Reuters', 'Al Jazeera'],
  },
  {
    eventName: 'Oil Production Collapses',
    eventDescription: 'Libyan oil production drops from 1.6M to 0.2M barrels/day',
    eventCategory: 'economic',
    eventDate: '2014-07-01',
    country: 'Libya',
    estimatedGMI: 20,
    estimatedCFI: 90,
    estimatedHRI: 15,
    emotionalVector: { joy: 5, fear: 90, anger: 80, sadness: 70, hope: 10, curiosity: 35 },
    gdpImpact: -45,
    shortTermOutcome: 'Currency devaluation, inflation spike',
    mediumTermOutcome: 'Unemployment rises, public services collapse',
    longTermOutcome: 'Economic crisis, dependency on imports',
    sources: ['OPEC', 'Reuters', 'World Bank'],
  },
  {
    eventName: 'Dinar Currency Crisis',
    eventDescription: 'Libyan dinar loses 50% of its value against USD',
    eventCategory: 'economic',
    eventDate: '2015-03-15',
    country: 'Libya',
    estimatedGMI: 15,
    estimatedCFI: 95,
    estimatedHRI: 10,
    emotionalVector: { joy: 2, fear: 95, anger: 85, sadness: 80, hope: 5, curiosity: 30 },
    gdpImpact: -30,
    shortTermOutcome: 'Panic buying, hoarding behavior',
    mediumTermOutcome: 'Informal economy grows, black market thrives',
    longTermOutcome: 'Economic informalization, reduced government revenue',
    sources: ['IMF', 'Central Bank of Libya', 'Reuters'],
  },
  {
    eventName: 'ISIS Gains Territory',
    eventDescription: 'ISIS establishes presence in Sirte and surrounding areas',
    eventCategory: 'conflict',
    eventDate: '2015-02-16',
    country: 'Libya',
    estimatedGMI: 10,
    estimatedCFI: 98,
    estimatedHRI: 5,
    emotionalVector: { joy: 1, fear: 98, anger: 90, sadness: 85, hope: 2, curiosity: 40 },
    gdpImpact: -20,
    shortTermOutcome: 'Civilian evacuations, international concern',
    mediumTermOutcome: 'Military operations against ISIS',
    longTermOutcome: 'ISIS defeated but instability remains',
    sources: ['Reuters', 'BBC', 'SOCOM'],
  },
  {
    eventName: 'UN-Backed Government Established',
    eventDescription: 'Government of National Accord (GNA) recognized by UN',
    eventCategory: 'political',
    eventDate: '2016-03-30',
    country: 'Libya',
    estimatedGMI: 50,
    estimatedCFI: 60,
    estimatedHRI: 65,
    emotionalVector: { joy: 45, fear: 55, anger: 40, sadness: 35, hope: 70, curiosity: 65 },
    gdpImpact: 2,
    shortTermOutcome: 'International recognition, aid pledges',
    mediumTermOutcome: 'Gradual stabilization efforts begin',
    longTermOutcome: 'Slow recovery, ongoing challenges',
    sources: ['UN News', 'Reuters', 'BBC'],
  },
  {
    eventName: 'Tripoli Airport Reopens',
    eventDescription: 'Mitiga International Airport reopens after years of closure',
    eventCategory: 'economic',
    eventDate: '2016-06-15',
    country: 'Libya',
    estimatedGMI: 60,
    estimatedCFI: 50,
    estimatedHRI: 70,
    emotionalVector: { joy: 65, fear: 40, anger: 30, sadness: 25, hope: 75, curiosity: 60 },
    gdpImpact: 5,
    shortTermOutcome: 'Tourism and trade resume',
    mediumTermOutcome: 'Economic activity increases',
    longTermOutcome: 'Tourism sector recovery begins',
    sources: ['Reuters', 'Al Jazeera', 'BBC'],
  },
  {
    eventName: 'Oil Production Partially Recovers',
    eventDescription: 'Libyan oil production rises to 400,000 barrels/day',
    eventCategory: 'economic',
    eventDate: '2017-01-15',
    country: 'Libya',
    estimatedGMI: 65,
    estimatedCFI: 45,
    estimatedHRI: 75,
    emotionalVector: { joy: 70, fear: 35, anger: 25, sadness: 20, hope: 80, curiosity: 55 },
    gdpImpact: 12,
    shortTermOutcome: 'Government revenue increases',
    mediumTermOutcome: 'Salary payments resume, public services improve',
    longTermOutcome: 'Economic stabilization continues',
    sources: ['OPEC', 'Reuters', 'World Bank'],
  },

  // MENA Regional Events
  {
    eventName: 'Arab Spring Begins',
    eventDescription: 'Pro-democracy protests spread across MENA region',
    eventCategory: 'social',
    eventDate: '2010-12-17',
    country: 'Tunisia',
    estimatedGMI: 60,
    estimatedCFI: 55,
    estimatedHRI: 80,
    emotionalVector: { joy: 65, fear: 45, anger: 60, sadness: 30, hope: 85, curiosity: 75 },
    gdpImpact: -8,
    shortTermOutcome: 'Regime change in Tunisia, regional spread',
    mediumTermOutcome: 'Multiple countries experience uprisings',
    longTermOutcome: 'Mixed outcomes across region',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Egyptian Revolution',
    eventDescription: 'Mubarak regime falls after 30 years',
    eventCategory: 'political',
    eventDate: '2011-02-11',
    country: 'Egypt',
    estimatedGMI: 70,
    estimatedCFI: 50,
    estimatedHRI: 85,
    emotionalVector: { joy: 75, fear: 40, anger: 50, sadness: 20, hope: 90, curiosity: 80 },
    gdpImpact: -5,
    shortTermOutcome: 'Military takes interim control, optimism',
    mediumTermOutcome: 'Constitutional debates, elections',
    longTermOutcome: 'New government established',
    sources: ['Reuters', 'BBC', 'AP News'],
  },
  {
    eventName: 'Syrian Civil War Escalates',
    eventDescription: 'Syrian conflict intensifies with international involvement',
    eventCategory: 'conflict',
    eventDate: '2013-08-21',
    country: 'Syria',
    estimatedGMI: 15,
    estimatedCFI: 95,
    estimatedHRI: 10,
    emotionalVector: { joy: 5, fear: 95, anger: 85, sadness: 90, hope: 5, curiosity: 50 },
    gdpImpact: -50,
    shortTermOutcome: 'Humanitarian crisis, refugee flows',
    mediumTermOutcome: 'Regional destabilization',
    longTermOutcome: 'Prolonged conflict, millions displaced',
    sources: ['Reuters', 'BBC', 'UN News'],
  },
  {
    eventName: 'Saudi-Led Coalition Intervention in Yemen',
    eventDescription: 'Saudi Arabia leads military intervention in Yemen',
    eventCategory: 'conflict',
    eventDate: '2015-03-26',
    country: 'Yemen',
    estimatedGMI: 20,
    estimatedCFI: 90,
    estimatedHRI: 15,
    emotionalVector: { joy: 10, fear: 90, anger: 80, sadness: 85, hope: 10, curiosity: 45 },
    gdpImpact: -40,
    shortTermOutcome: 'Airstrikes begin, humanitarian concerns',
    mediumTermOutcome: 'Prolonged conflict, economic collapse',
    longTermOutcome: 'World\'s worst humanitarian crisis',
    sources: ['Reuters', 'BBC', 'UN News'],
  },
  {
    eventName: 'Iran Nuclear Deal Signed',
    eventDescription: 'JCPOA nuclear agreement reached',
    eventCategory: 'political',
    eventDate: '2015-07-14',
    country: 'Iran',
    estimatedGMI: 70,
    estimatedCFI: 40,
    estimatedHRI: 80,
    emotionalVector: { joy: 75, fear: 30, anger: 25, sadness: 15, hope: 85, curiosity: 70 },
    gdpImpact: 8,
    shortTermOutcome: 'Sanctions relief, economic opening',
    mediumTermOutcome: 'Regional tensions ease slightly',
    longTermOutcome: 'Temporary stability, later reversed',
    sources: ['Reuters', 'BBC', 'AP News'],
  },
  {
    eventName: 'Refugee Crisis Peaks',
    eventDescription: 'Over 1 million refugees reach Europe',
    eventCategory: 'social',
    eventDate: '2015-09-02',
    country: 'MENA',
    estimatedGMI: 30,
    estimatedCFI: 75,
    estimatedHRI: 40,
    emotionalVector: { joy: 20, fear: 75, anger: 65, sadness: 80, hope: 35, curiosity: 60 },
    gdpImpact: -10,
    shortTermOutcome: 'European border closures, political backlash',
    mediumTermOutcome: 'Refugee camps expand, humanitarian crisis',
    longTermOutcome: 'Long-term displacement, integration challenges',
    sources: ['UN UNHCR', 'Reuters', 'BBC'],
  },
  {
    eventName: 'ISIS Caliphate Declared',
    eventDescription: 'ISIS declares Islamic State in Iraq and Syria',
    eventCategory: 'conflict',
    eventDate: '2014-06-29',
    country: 'Iraq',
    estimatedGMI: 5,
    estimatedCFI: 99,
    estimatedHRI: 2,
    emotionalVector: { joy: 1, fear: 99, anger: 95, sadness: 90, hope: 1, curiosity: 55 },
    gdpImpact: -60,
    shortTermOutcome: 'Rapid territorial expansion, mass displacement',
    mediumTermOutcome: 'International coalition forms, military operations',
    longTermOutcome: 'Caliphate defeated but terrorism continues',
    sources: ['Reuters', 'BBC', 'SOCOM'],
  },
  {
    eventName: 'Saudi-Iran Tensions Rise',
    eventDescription: 'Saudi Arabia executes Iranian cleric, tensions escalate',
    eventCategory: 'political',
    eventDate: '2016-01-02',
    country: 'Saudi Arabia',
    estimatedGMI: 25,
    estimatedCFI: 85,
    estimatedHRI: 20,
    emotionalVector: { joy: 10, fear: 85, anger: 80, sadness: 50, hope: 15, curiosity: 65 },
    gdpImpact: -5,
    shortTermOutcome: 'Diplomatic crisis, proxy conflicts intensify',
    mediumTermOutcome: 'Regional polarization deepens',
    longTermOutcome: 'Ongoing regional rivalry',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Oil Price Collapse',
    eventDescription: 'Global oil prices fall below $30/barrel',
    eventCategory: 'economic',
    eventDate: '2016-01-20',
    country: 'MENA',
    estimatedGMI: 20,
    estimatedCFI: 85,
    estimatedHRI: 25,
    emotionalVector: { joy: 15, fear: 85, anger: 75, sadness: 70, hope: 20, curiosity: 50 },
    gdpImpact: -25,
    shortTermOutcome: 'Government budgets slashed, austerity measures',
    mediumTermOutcome: 'Economic contraction, unemployment rises',
    longTermOutcome: 'Structural economic reforms needed',
    sources: ['OPEC', 'Reuters', 'World Bank'],
  },

  // Additional Events
  {
    eventName: 'Turkish Coup Attempt',
    eventDescription: 'Failed military coup in Turkey',
    eventCategory: 'political',
    eventDate: '2016-07-15',
    country: 'Turkey',
    estimatedGMI: 30,
    estimatedCFI: 80,
    estimatedHRI: 35,
    emotionalVector: { joy: 25, fear: 80, anger: 75, sadness: 60, hope: 40, curiosity: 70 },
    gdpImpact: -8,
    shortTermOutcome: 'Government consolidation, purges begin',
    mediumTermOutcome: 'Political polarization increases',
    longTermOutcome: 'Authoritarian tendencies strengthen',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Qatar Blockade Begins',
    eventDescription: 'Saudi-led coalition imposes blockade on Qatar',
    eventCategory: 'political',
    eventDate: '2017-06-05',
    country: 'Qatar',
    estimatedGMI: 35,
    estimatedCFI: 75,
    estimatedHRI: 40,
    emotionalVector: { joy: 25, fear: 75, anger: 70, sadness: 55, hope: 45, curiosity: 65 },
    gdpImpact: -15,
    shortTermOutcome: 'Diplomatic crisis, economic pressure',
    mediumTermOutcome: 'Regional divisions deepen',
    longTermOutcome: 'Blockade continues for years',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Morocco-Algeria Border Tensions',
    eventDescription: 'Military buildup along Morocco-Algeria border',
    eventCategory: 'conflict',
    eventDate: '2015-06-10',
    country: 'Morocco',
    estimatedGMI: 40,
    estimatedCFI: 70,
    estimatedHRI: 45,
    emotionalVector: { joy: 30, fear: 70, anger: 65, sadness: 45, hope: 50, curiosity: 60 },
    gdpImpact: -3,
    shortTermOutcome: 'Diplomatic tensions, military exercises',
    mediumTermOutcome: 'Border remains tense',
    longTermOutcome: 'Occasional skirmishes, no major conflict',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Jordan Refugee Crisis',
    eventDescription: 'Over 1 million Syrian refugees in Jordan',
    eventCategory: 'social',
    eventDate: '2016-03-15',
    country: 'Jordan',
    estimatedGMI: 35,
    estimatedCFI: 70,
    estimatedHRI: 45,
    emotionalVector: { joy: 25, fear: 70, anger: 60, sadness: 75, hope: 50, curiosity: 55 },
    gdpImpact: -8,
    shortTermOutcome: 'Humanitarian aid, international support',
    mediumTermOutcome: 'Strain on resources, social tensions',
    longTermOutcome: 'Long-term integration challenges',
    sources: ['UN UNHCR', 'Reuters', 'BBC'],
  },
  {
    eventName: 'Lebanon Political Crisis',
    eventDescription: 'Lebanon\'s government formation stalls',
    eventCategory: 'political',
    eventDate: '2016-10-31',
    country: 'Lebanon',
    estimatedGMI: 30,
    estimatedCFI: 75,
    estimatedHRI: 35,
    emotionalVector: { joy: 20, fear: 75, anger: 70, sadness: 60, hope: 40, curiosity: 60 },
    gdpImpact: -5,
    shortTermOutcome: 'Political deadlock, no government',
    mediumTermOutcome: 'Economic stagnation, services decline',
    longTermOutcome: 'Government eventually formed',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Palestine-Israel Escalation',
    eventDescription: 'Violence escalates in Palestinian territories',
    eventCategory: 'conflict',
    eventDate: '2015-10-01',
    country: 'Palestine',
    estimatedGMI: 20,
    estimatedCFI: 85,
    estimatedHRI: 25,
    emotionalVector: { joy: 10, fear: 85, anger: 80, sadness: 80, hope: 20, curiosity: 65 },
    gdpImpact: -10,
    shortTermOutcome: 'Casualties, international condemnation',
    mediumTermOutcome: 'Humanitarian concerns, aid appeals',
    longTermOutcome: 'Ongoing conflict, periodic escalations',
    sources: ['Reuters', 'BBC', 'Al Jazeera'],
  },
  {
    eventName: 'Tunisia Democratic Progress',
    eventDescription: 'Tunisia adopts new constitution, elections held',
    eventCategory: 'political',
    eventDate: '2014-01-26',
    country: 'Tunisia',
    estimatedGMI: 70,
    estimatedCFI: 40,
    estimatedHRI: 80,
    emotionalVector: { joy: 75, fear: 30, anger: 25, sadness: 15, hope: 85, curiosity: 75 },
    gdpImpact: 3,
    shortTermOutcome: 'Democratic transition, international praise',
    mediumTermOutcome: 'Stable governance, economic recovery',
    longTermOutcome: 'Tunisia becomes regional democratic model',
    sources: ['Reuters', 'BBC', 'UN News'],
  },
  {
    eventName: 'Morocco Economic Growth',
    eventDescription: 'Morocco achieves 3% GDP growth',
    eventCategory: 'economic',
    eventDate: '2016-12-31',
    country: 'Morocco',
    estimatedGMI: 65,
    estimatedCFI: 45,
    estimatedHRI: 75,
    emotionalVector: { joy: 70, fear: 35, anger: 25, sadness: 20, hope: 80, curiosity: 60 },
    gdpImpact: 3,
    shortTermOutcome: 'Job creation, consumer confidence rises',
    mediumTermOutcome: 'Continued growth, investment increases',
    longTermOutcome: 'Morocco becomes regional economic leader',
    sources: ['World Bank', 'Reuters', 'IMF'],
  },
];

/**
 * Get sample historical events
 */
export function getSampleHistoricalEvents() {
  return historicalEventsData;
}

/**
 * Get events by country
 */
export function getEventsByCountry(country: string) {
  return historicalEventsData.filter(e => e.country === country || e.country === 'MENA');
}

/**
 * Get events by category
 */
export function getEventsByCategory(category: string) {
  return historicalEventsData.filter(e => e.eventCategory === category);
}

/**
 * Get events by date range
 */
export function getEventsByDateRange(startDate: string, endDate: string) {
  return historicalEventsData.filter(e => e.eventDate >= startDate && e.eventDate <= endDate);
}
