/**
 * EXPORT DATA COMPONENT
 * 
 * تصدير البيانات
 * - تصدير بصيغ متعددة (PDF, CSV, JSON)
 * - مشاركة البيانات
 * - جدولة التصدير التلقائي
 */

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Download, Share2, FileText, Table, Code, Mail, Copy, CheckCircle } from 'lucide-react';

interface ExportOption {
  id: string;
  name: string;
  format: string;
  description: string;
  icon: React.ReactNode;
  fileExtension: string;
  mimeType: string;
}

interface ExportDataProps {
  data?: any;
  title?: string;
  onExport?: (format: string) => void;
}

export function ExportData({
  data,
  title = 'البيانات المصدرة',
  onExport
}: ExportDataProps) {
  const [selectedFormat, setSelectedFormat] = useState<string | null>(null);
  const [includeMetadata, setIncludeMetadata] = useState(true);
  const [includeCharts, setIncludeCharts] = useState(true);
  const [dateRange, setDateRange] = useState('all');
  const [shareLink, setShareLink] = useState<string | null>(null);
  const [exportStatus, setExportStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [copiedLink, setCopiedLink] = useState(false);

  const exportOptions: ExportOption[] = [
    {
      id: 'pdf',
      name: 'PDF',
      format: 'PDF Document',
      description: 'تقرير احترافي بصيغة PDF مع الرسوم البيانية',
      icon: <FileText className="w-6 h-6" />,
      fileExtension: 'pdf',
      mimeType: 'application/pdf'
    },
    {
      id: 'csv',
      name: 'CSV',
      format: 'Spreadsheet',
      description: 'بيانات جدولية قابلة للتحرير في Excel',
      icon: <Table className="w-6 h-6" />,
      fileExtension: 'csv',
      mimeType: 'text/csv'
    },
    {
      id: 'json',
      name: 'JSON',
      format: 'Data Format',
      description: 'بيانات منظمة بصيغة JSON للمعالجة البرمجية',
      icon: <Code className="w-6 h-6" />,
      fileExtension: 'json',
      mimeType: 'application/json'
    }
  ];

  const handleExport = async (format: string) => {
    setExportStatus('loading');
    setSelectedFormat(format);

    try {
      // Simulate export process
      await new Promise(resolve => setTimeout(resolve, 1500));

      // Generate mock data based on format
      let content = '';
      let filename = `${title}-${new Date().toISOString().split('T')[0]}.${format}`;

      switch (format) {
        case 'pdf':
          content = generatePDFContent();
          break;
        case 'csv':
          content = generateCSVContent();
          break;
        case 'json':
          content = generateJSONContent();
          break;
      }

      // Create download link
      const blob = new Blob([content], { mimeType: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setExportStatus('success');
      onExport?.(format);

      // Reset status after 2 seconds
      setTimeout(() => setExportStatus('idle'), 2000);
    } catch (error) {
      setExportStatus('error');
      setTimeout(() => setExportStatus('idle'), 2000);
    }
  };

  const generatePDFContent = () => {
    return `
PDF Report - ${title}
Generated: ${new Date().toLocaleString('ar-SA')}

Summary:
- Total Records: 1,250
- Date Range: ${dateRange}
- Metadata Included: ${includeMetadata ? 'Yes' : 'No'}
- Charts Included: ${includeCharts ? 'Yes' : 'No'}

Data Summary:
- Global Mood Index (GMI): 65.4
- Collective Fear Index (CFI): 42.1
- Hope Resilience Index (HRI): 71.8

Top Topics:
1. الاقتصاد العالمي - 2,450 mentions
2. التطورات التكنولوجية - 1,890 mentions
3. التغيرات المناخية - 1,650 mentions

Emotional Distribution:
- Hope: 35%
- Curiosity: 28%
- Concern: 22%
- Joy: 15%

Report Generated by AmalSense
    `;
  };

  const generateCSVContent = () => {
    return `Date,Topic,GMI,CFI,HRI,Emotion,Confidence
2024-03-03,الاقتصاد العالمي,65.4,42.1,71.8,قلق,0.85
2024-03-03,التطورات التكنولوجية,72.1,35.2,78.5,أمل,0.92
2024-03-03,التغيرات المناخية,58.3,55.7,62.1,قلق,0.78
2024-03-02,السياسة الدولية,63.2,48.9,68.4,فضول,0.81
2024-03-02,الأخبار الاقتصادية,67.8,40.3,74.2,أمل,0.88
2024-03-01,الأسواق المالية,64.1,43.5,70.1,قلق,0.83
    `;
  };

  const generateJSONContent = () => {
    return JSON.stringify({
      report: {
        title: title,
        generatedAt: new Date().toISOString(),
        metadata: {
          includeMetadata,
          includeCharts,
          dateRange
        },
        summary: {
          totalRecords: 1250,
          gmi: 65.4,
          cfi: 42.1,
          hri: 71.8
        },
        topTopics: [
          { rank: 1, name: 'الاقتصاد العالمي', mentions: 2450 },
          { rank: 2, name: 'التطورات التكنولوجية', mentions: 1890 },
          { rank: 3, name: 'التغيرات المناخية', mentions: 1650 }
        ],
        emotionalDistribution: {
          hope: 35,
          curiosity: 28,
          concern: 22,
          joy: 15
        }
      }
    }, null, 2);
  };

  const handleShare = async () => {
    // Generate share link
    const link = `https://amalsense.com/share/${Math.random().toString(36).substr(2, 9)}`;
    setShareLink(link);

    // Copy to clipboard
    try {
      await navigator.clipboard.writeText(link);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-black">تصدير البيانات</h2>
          <p className="text-sm text-gray-600 mt-1">
            صدّر البيانات بصيغ متعددة وشارك النتائج
          </p>
        </div>
      </div>

      {/* Export Options */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {exportOptions.map(option => (
          <Card
            key={option.id}
            className={`p-6 border-2 cursor-pointer transition ${
              selectedFormat === option.id
                ? 'border-black bg-black bg-opacity-5'
                : 'border-gray-200 hover:border-gray-400'
            }`}
            onClick={() => setSelectedFormat(option.id)}
          >
            <div className="flex flex-col items-center text-center gap-3">
              <div className={selectedFormat === option.id ? 'text-black' : 'text-gray-600'}>
                {option.icon}
              </div>
              <div>
                <h3 className="font-semibold text-black">{option.name}</h3>
                <p className="text-xs text-gray-600 mt-1">{option.format}</p>
                <p className="text-xs text-gray-600 mt-2">{option.description}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Export Settings */}
      <Card className="p-6 border border-gray-200">
        <h3 className="font-semibold text-black mb-4">إعدادات التصدير</h3>

        <div className="space-y-4">
          {/* Date Range */}
          <div>
            <label className="text-sm font-medium text-gray-700 mb-2 block">نطاق التاريخ</label>
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-black"
            >
              <option value="all">الكل</option>
              <option value="week">آخر أسبوع</option>
              <option value="month">آخر شهر</option>
              <option value="quarter">آخر ربع سنة</option>
              <option value="year">آخر سنة</option>
            </select>
          </div>

          {/* Include Options */}
          <div className="space-y-2">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={includeMetadata}
                onChange={(e) => setIncludeMetadata(e.target.checked)}
                className="w-4 h-4"
              />
              <span className="text-sm text-gray-700">تضمين البيانات الوصفية</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={includeCharts}
                onChange={(e) => setIncludeCharts(e.target.checked)}
                className="w-4 h-4"
              />
              <span className="text-sm text-gray-700">تضمين الرسوم البيانية</span>
            </label>
          </div>
        </div>
      </Card>

      {/* Export Actions */}
      <div className="flex gap-3">
        <Button
          onClick={() => selectedFormat && handleExport(selectedFormat)}
          disabled={!selectedFormat || exportStatus === 'loading'}
          className={`gap-2 flex-1 ${
            selectedFormat && exportStatus !== 'loading'
              ? 'bg-black text-white hover:bg-gray-800'
              : 'bg-gray-200 text-gray-600 cursor-not-allowed'
          }`}
        >
          {exportStatus === 'loading' && (
            <div className="animate-spin">⏳</div>
          )}
          {exportStatus === 'success' && (
            <CheckCircle className="w-4 h-4" />
          )}
          {exportStatus === 'idle' && (
            <Download className="w-4 h-4" />
          )}
          {exportStatus === 'loading' ? 'جاري التصدير...' : 'تحميل'}
        </Button>

        <Button
          onClick={handleShare}
          className="gap-2 bg-gray-100 text-black hover:bg-gray-200"
        >
          <Share2 className="w-4 h-4" />
          مشاركة
        </Button>
      </div>

      {/* Share Link */}
      {shareLink && (
        <Card className="p-4 border border-gray-200 bg-gray-50">
          <p className="text-sm text-gray-700 mb-2">رابط المشاركة:</p>
          <div className="flex items-center gap-2">
            <code className="flex-1 bg-white px-3 py-2 rounded border border-gray-300 text-xs break-all">
              {shareLink}
            </code>
            <button
              onClick={() => {
                navigator.clipboard.writeText(shareLink);
                setCopiedLink(true);
                setTimeout(() => setCopiedLink(false), 2000);
              }}
              className="p-2 rounded bg-black text-white hover:bg-gray-800 transition"
            >
              <Copy className="w-4 h-4" />
            </button>
          </div>
          {copiedLink && (
            <p className="text-xs text-green-600 mt-2">✓ تم النسخ إلى الحافظة</p>
          )}
        </Card>
      )}

      {/* Export History */}
      <Card className="p-6 border border-gray-200">
        <h3 className="font-semibold text-black mb-4">سجل التصديرات</h3>
        <div className="space-y-2">
          {[
            { date: '2024-03-03 14:30', format: 'PDF', size: '2.4 MB', status: 'نجح' },
            { date: '2024-03-03 12:15', format: 'CSV', size: '156 KB', status: 'نجح' },
            { date: '2024-03-02 18:45', format: 'JSON', size: '89 KB', status: 'نجح' }
          ].map((item, idx) => (
            <div key={idx} className="flex items-center justify-between p-3 bg-gray-50 rounded">
              <div>
                <p className="text-sm font-medium text-black">{item.format}</p>
                <p className="text-xs text-gray-600">{item.date}</p>
              </div>
              <div className="flex items-center gap-3">
                <span className="text-xs text-gray-600">{item.size}</span>
                <Badge className="bg-green-100 text-green-800 text-xs">
                  {item.status}
                </Badge>
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Scheduled Exports */}
      <Card className="p-6 border border-gray-200">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-black">التصديرات المجدولة</h3>
          <Button className="gap-2 bg-black text-white hover:bg-gray-800 text-sm">
            <Plus className="w-4 h-4" />
            جدولة جديدة
          </Button>
        </div>

        <div className="space-y-2">
          {[
            { schedule: 'أسبوعي', day: 'الأحد', time: '09:00', format: 'PDF', email: 'user@example.com' },
            { schedule: 'شهري', day: 'أول يوم', time: '08:00', format: 'CSV', email: 'user@example.com' }
          ].map((item, idx) => (
            <div key={idx} className="flex items-center justify-between p-3 bg-gray-50 rounded">
              <div>
                <p className="text-sm font-medium text-black">
                  {item.schedule} - {item.format}
                </p>
                <p className="text-xs text-gray-600">
                  {item.day} في {item.time} → {item.email}
                </p>
              </div>
              <Button
                variant="outline"
                size="sm"
                className="text-xs"
              >
                تعديل
              </Button>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

// Add missing import
import { Plus } from 'lucide-react';
